FROM golang:1.11.5

LABEL maintainer="jblaskowich@gmail.com"

WORKDIR /

RUN go get -v -d github.com/go-sql-driver/mysql

RUN go get -v -d github.com/nats-io/go-nats

RUN go get -v -d github.com/opentracing/opentracing-go

RUN go get -v -d github.com/uber/jaeger-client-go

RUN go get -v -d github.com/pkg/errors

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM scratch  

COPY --from=0 app /

ENTRYPOINT ["/app"]